name: binn-grf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - h5py
  - pyyaml
  - matplotlib
  - optuna
  - tensorboard
